using System.Text.Json;
using System.Text.Json.Serialization;
using MEFrpLauncherX.Core;
using MEFrpLauncherX.Core.Storage;
using MEFrpLauncherX.Core.Styling;
using RYCB.PML.MEFrpCaptchaLib;
using static MEFrpLauncherX.Core.MEFIntergrated.InfoClasses;

namespace MEFrpLauncherX;

[JsonSerializable(typeof(ApiInfo<UserInfo>))]
[JsonSerializable(typeof(ApiInfo<SignInfo>))]
[JsonSerializable(typeof(ApiInfo<ConfigInfo>))]
[JsonSerializable(typeof(ApiInfo<TrafficStatus>))]
[JsonSerializable(typeof(ApiInfo<FrpTokenInfo>))]
[JsonSerializable(typeof(ApiInfo<ProxyInfo>))]
[JsonSerializable(typeof(ApiInfo<NodesListInfo>))]
[JsonSerializable(typeof(ApiInfo<NodeNameList>))]
[JsonSerializable(typeof(ApiInfo<NodesStatusInfo>))]
[JsonSerializable(typeof(ApiInfo<PublicData>))]
[JsonSerializable(typeof(ApiInfo<SystemStatus>))]
[JsonSerializable(typeof(ApiInfo<ExtraUserInfo>))]
[JsonSerializable(typeof(ApiInfo<string>))]
[JsonSerializable(typeof(ApiInfo<string?>))]
[JsonSerializable(typeof(ApiInfo<int>))]
[JsonSerializable(typeof(ApiInfo<object>))]
[JsonSerializable(typeof(ApiInfo<NodeStatus[]>))]
[JsonSerializable(typeof(ApiInfo<NodeInfo[]>))]
[JsonSerializable(typeof(ApiInfo<NodeNameList[]>))]
[JsonSerializable(typeof(ApiInfo<SystemStatus?>))]
[JsonSerializable(typeof(SignInfo))]
[JsonSerializable(typeof(ConfigInfo))]
[JsonSerializable(typeof(TrafficStatus))]
[JsonSerializable(typeof(FrpTokenInfo))]
[JsonSerializable(typeof(ProxyInfo))]
[JsonSerializable(typeof(Nodes))]
[JsonSerializable(typeof(Proxies))]
[JsonSerializable(typeof(NodesListInfo))]
[JsonSerializable(typeof(NodeInfo))]
[JsonSerializable(typeof(NodeNameList))]
[JsonSerializable(typeof(NodesStatusInfo))]
[JsonSerializable(typeof(NodeStatus))]
[JsonSerializable(typeof(PublicData))]
[JsonSerializable(typeof(SystemStatus))]
[JsonSerializable(typeof(UserInfo4Login))]
[JsonSerializable(typeof(VaptchaInfo))]
[JsonSerializable(typeof(LoginInfo))]
[JsonSerializable(typeof(ExtraUserInfo))]
[JsonSerializable(typeof(ChallengeInfo))]
[JsonSerializable(typeof(CaptchaResultX))]
[JsonSerializable(typeof(FeedbackBody))]
[JsonSerializable(typeof(FeedbackResponse))]
[JsonSerializable(typeof(EmailBody))]
[JsonSerializable(typeof(SingleVersionInfo))]
[JsonSerializable(typeof(NoticeContent))]
[JsonSerializable(typeof(TunnelErrorInfosShell))]
[JsonSerializable(typeof(SingleApiInfo<TunnelErrorInfo>))]
[JsonSerializable(typeof(SingleApiInfo<NoticeContent[]>))]
[JsonSerializable(typeof(TunnelErrorInfo))]
[JsonSerializable(typeof(AppConfig))]
[JsonSerializable(typeof(UpdateSettings))]
[JsonSerializable(typeof(BackgroundSettings))]
[JsonSerializable(typeof(PFSConfig))]
[JsonSerializable(typeof(ALPConfig))]
[JsonSerializable(typeof(List<ALPConfig>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(KickProxyInfo))]
[JsonSerializable(typeof(ToggleProxyInfo))]
[JsonSerializable(typeof(FreePortBody))]
[JsonSerializable(typeof(ThemeManifest))]
[JsonSerializable(typeof(AccentMeta))]
[JsonSerializable(typeof(DatePeriod))]
[JsonSerializable(typeof(SignPost))]
[JsonSerializable(typeof(LaunchConfigRequest))]
[JsonSerializable(typeof(DeleteProxyInfo))]
[JsonSerializable(typeof(SecureUserInfo))]
[JsonSerializable(typeof(LocationNameInfo[]))]
[JsonSourceGenerationOptions(IncludeFields = true, PropertyNameCaseInsensitive = true)]
public partial class AppJsonSerializerContext : JsonSerializerContext
{
}