<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MEFrpLauncherX.Core\MEFrpLauncherX.Core.csproj" />
      <ProjectReference Include="..\MEFrpLauncherX\MEFrpLauncherX.csproj" />
    </ItemGroup>

</Project>
