//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFrpLauncherX.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MEFrpLauncherX.Core.Languages.Languages.en-US", typeof(Languages_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Text_Global_Cancel {
            get {
                return ResourceManager.GetString("Text.Global.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Text_Global_Confirm {
            get {
                return ResourceManager.GetString("Text.Global.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Text_Global_Failed {
            get {
                return ResourceManager.GetString("Text.Global.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Text_Global_Success {
            get {
                return ResourceManager.GetString("Text.Global.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA method.
        /// </summary>
        public static string Text_Login_AuthMode {
            get {
                return ResourceManager.GetString("Text.Login.AuthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free, public welfare, user-friendly, low-latency and stable FRP service.
        /// </summary>
        public static string Text_Login_MEFrpFeature_1 {
            get {
                return ResourceManager.GetString("Text.Login.MEFrpFeature.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six years of accumulation · Brand-new upgrade · A stable and efficient FRP tool.
        /// </summary>
        public static string Text_Login_MEFrpFeature_2 {
            get {
                return ResourceManager.GetString("Text.Login.MEFrpFeature.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in via AcmeCloud account.
        /// </summary>
        public static string Text_Login_Method_Acme {
            get {
                return ResourceManager.GetString("Text.Login.Method.Acme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in via ME Frp account.
        /// </summary>
        public static string Text_Login_Method_MEFrp {
            get {
                return ResourceManager.GetString("Text.Login.Method.MEFrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Text_Login_Password {
            get {
                return ResourceManager.GetString("Text.Login.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Text_Login_Register {
            get {
                return ResourceManager.GetString("Text.Login.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Text_Login_RememberMe {
            get {
                return ResourceManager.GetString("Text.Login.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Text_Login_Username {
            get {
                return ResourceManager.GetString("Text.Login.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To ME Frp.
        /// </summary>
        public static string Text_Login_Welcome {
            get {
                return ResourceManager.GetString("Text.Login.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing necessary resources.
        /// </summary>
        public static string Text_Main_Initialize_Resource {
            get {
                return ResourceManager.GetString("Text.Main.Initialize.Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string Text_Main_Initialize_Title {
            get {
                return ResourceManager.GetString("Text.Main.Initialize.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Notices.
        /// </summary>
        public static string Text_Main_PlatformNotice_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformNotice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Nodes {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Proxies.
        /// </summary>
        public static string Text_Main_PlatformStatistics_OnlineProxies {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.OnlineProxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Statistics.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Traffic {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Users {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgraded Service.
        /// </summary>
        public static string Text_Main_PlatformStatus_Downgrade_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatus.Downgrade.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string Text_Main_PlatformStatus_NetworkError_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatus.NetworkError.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Normally.
        /// </summary>
        public static string Text_Main_PlatformStatus_Normal_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatus.Normal.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Service Failure.
        /// </summary>
        public static string Text_Main_PlatformStatusBreakdown_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatusBreakdown.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing update cache.
        /// </summary>
        public static string Text_Main_PostUpdateProcess_Cleaning {
            get {
                return ResourceManager.GetString("Text.Main.PostUpdateProcess.Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undergoing post-update cleaning.
        /// </summary>
        public static string Text_Main_PostUpdateProcess_Title {
            get {
                return ResourceManager.GetString("Text.Main.PostUpdateProcess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Notices.
        /// </summary>
        public static string Text_Main_SoftwareNotice_Title {
            get {
                return ResourceManager.GetString("Text.Main.SoftwareNotice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Status.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_Banned {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_Normal {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Limit Exceeded.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_OverTraffic {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.OverTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_Unknown {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Text_Main_UserInfo_Email {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Text_Main_UserInfo_Group {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Text_Main_UserInfo_Id {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Bandwidth.
        /// </summary>
        public static string Text_Main_UserInfo_InboundBandwidth {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.InboundBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Text_Main_UserInfo_Name {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound Bandwidth.
        /// </summary>
        public static string Text_Main_UserInfo_OutboundBandwidth {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.OutboundBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Count.
        /// </summary>
        public static string Text_Main_UserInfo_ProxyCount {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.ProxyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-name Authentication Status.
        /// </summary>
        public static string Text_Main_UserInfo_RealNameAuthenticationStatus {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RealNameAuthenticationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated.
        /// </summary>
        public static string Text_Main_UserInfo_RealNameAuthenticationStatus_Authenticated {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RealNameAuthenticationStatus.Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthenticated.
        /// </summary>
        public static string Text_Main_UserInfo_RealNameAuthenticationStatus_UnAuthenticated {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RealNameAuthenticationStatus.UnAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Data Allowance.
        /// </summary>
        public static string Text_Main_UserInfo_RemainingTraffic {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RemainingTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed In.
        /// </summary>
        public static string Text_Main_UserInfo_SignedIn {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.SignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Text_Main_UserInfo_SignIn {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Text_Main_UserInfo_Title {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Title", resourceCulture);
            }
        }
    }
}
