//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFrpLauncherX.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MEFrpLauncherX.Core.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Text_Global_Cancel {
            get {
                return ResourceManager.GetString("Text.Global.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Text_Global_Confirm {
            get {
                return ResourceManager.GetString("Text.Global.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        public static string Text_Global_Failed {
            get {
                return ResourceManager.GetString("Text.Global.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Text_Global_Success {
            get {
                return ResourceManager.GetString("Text.Global.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人机验证方式.
        /// </summary>
        public static string Text_Login_AuthMode {
            get {
                return ResourceManager.GetString("Text.Login.AuthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 免费 · 公益 · 好用 · 低延迟 · 稳定的内网穿透服务.
        /// </summary>
        public static string Text_Login_MEFrpFeature_1 {
            get {
                return ResourceManager.GetString("Text.Login.MEFrpFeature.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六年沉淀 · 全新升级 · 稳定高效的内网穿透利器.
        /// </summary>
        public static string Text_Login_MEFrpFeature_2 {
            get {
                return ResourceManager.GetString("Text.Login.MEFrpFeature.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 云上极致 登录.
        /// </summary>
        public static string Text_Login_Method_Acme {
            get {
                return ResourceManager.GetString("Text.Login.Method.Acme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 ME Frp 登录.
        /// </summary>
        public static string Text_Login_Method_MEFrp {
            get {
                return ResourceManager.GetString("Text.Login.Method.MEFrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Text_Login_Password {
            get {
                return ResourceManager.GetString("Text.Login.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Text_Login_Register {
            get {
                return ResourceManager.GetString("Text.Login.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以后自动登录.
        /// </summary>
        public static string Text_Login_RememberMe {
            get {
                return ResourceManager.GetString("Text.Login.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string Text_Login_Username {
            get {
                return ResourceManager.GetString("Text.Login.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎来到 ME Frp 幻缘映射.
        /// </summary>
        public static string Text_Login_Welcome {
            get {
                return ResourceManager.GetString("Text.Login.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在解压资源.
        /// </summary>
        public static string Text_Main_Initialize_Resource {
            get {
                return ResourceManager.GetString("Text.Main.Initialize.Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PML 2 正在初始化.
        /// </summary>
        public static string Text_Main_Initialize_Title {
            get {
                return ResourceManager.GetString("Text.Main.Initialize.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统公告.
        /// </summary>
        public static string Text_Main_PlatformNotice_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformNotice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节点数.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Nodes {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线隧道.
        /// </summary>
        public static string Text_Main_PlatformStatistics_OnlineProxies {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.OnlineProxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计信息.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流量.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Traffic {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户数.
        /// </summary>
        public static string Text_Main_PlatformStatistics_Users {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatistics.Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统服务降级.
        /// </summary>
        public static string Text_Main_PlatformStatus_Downgrade_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatus.Downgrade.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络服务错误.
        /// </summary>
        public static string Text_Main_PlatformStatus_NetworkError_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatus.NetworkError.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统正常运行.
        /// </summary>
        public static string Text_Main_PlatformStatus_Normal_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatus.Normal.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统服务故障.
        /// </summary>
        public static string Text_Main_PlatformStatusBreakdown_Title {
            get {
                return ResourceManager.GetString("Text.Main.PlatformStatusBreakdown.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在清理更新缓存.
        /// </summary>
        public static string Text_Main_PostUpdateProcess_Cleaning {
            get {
                return ResourceManager.GetString("Text.Main.PostUpdateProcess.Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PML 2 正在进行更新后清理.
        /// </summary>
        public static string Text_Main_PostUpdateProcess_Title {
            get {
                return ResourceManager.GetString("Text.Main.PostUpdateProcess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件公告.
        /// </summary>
        public static string Text_Main_SoftwareNotice_Title {
            get {
                return ResourceManager.GetString("Text.Main.SoftwareNotice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户状态.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已封禁.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_Banned {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_Normal {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流量超限.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_OverTraffic {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.OverTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        public static string Text_Main_UserInfo_AccountStatus_Unknown {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.AccountStatus.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册邮箱.
        /// </summary>
        public static string Text_Main_UserInfo_Email {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户组.
        /// </summary>
        public static string Text_Main_UserInfo_Group {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户ID.
        /// </summary>
        public static string Text_Main_UserInfo_Id {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入站带宽.
        /// </summary>
        public static string Text_Main_UserInfo_InboundBandwidth {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.InboundBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string Text_Main_UserInfo_Name {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出站带宽.
        /// </summary>
        public static string Text_Main_UserInfo_OutboundBandwidth {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.OutboundBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隧道数量.
        /// </summary>
        public static string Text_Main_UserInfo_ProxyCount {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.ProxyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实名认证状态.
        /// </summary>
        public static string Text_Main_UserInfo_RealNameAuthenticationStatus {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RealNameAuthenticationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已实名.
        /// </summary>
        public static string Text_Main_UserInfo_RealNameAuthenticationStatus_Authenticated {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RealNameAuthenticationStatus.Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未实名.
        /// </summary>
        public static string Text_Main_UserInfo_RealNameAuthenticationStatus_UnAuthenticated {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RealNameAuthenticationStatus.UnAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余流量.
        /// </summary>
        public static string Text_Main_UserInfo_RemainingTraffic {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.RemainingTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已签到.
        /// </summary>
        public static string Text_Main_UserInfo_SignedIn {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.SignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 签到.
        /// </summary>
        public static string Text_Main_UserInfo_SignIn {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户信息.
        /// </summary>
        public static string Text_Main_UserInfo_Title {
            get {
                return ResourceManager.GetString("Text.Main.UserInfo.Title", resourceCulture);
            }
        }
    }
}
