//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class MarkdownRender
    {
        public static readonly string CopyButtonContent = "Localization.MarkdownRender.CopyButtonContent";
        public static readonly string CopyNotificationTitle = "Localization.MarkdownRender.CopyNotificationTitle";
        public static readonly string CopyNotificationMessage = "Localization.MarkdownRender.CopyNotificationMessage";
    }
}
