<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <!-- 版本统一由仓库根目录 Directory.Packages.props 中央管理 -->
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="SkiaSharp" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
        <PackageReference Include="SkiaSharp.NativeAssets.macOS" />
        <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
    </ItemGroup>
</Project>
