; Script generated by the Inno Setup Script Wizard.
; Non-commercial use only
; 路径均相对本脚本所在目录（installer/），本地与 CI 通用。
; CI 可通过 ISCC /DMyAppVersion=... /DOutDir=... 覆盖（配合 #ifndef）。
#include "idp.iss"

#define MyAppName "PML 2"
#ifndef MyAppVersion
  #define MyAppVersion "26.2.0"
#endif
#define MyAppPublisher "RYCB Studio"
#define MyAppURL "https://www.rycb.tech/pml-2"
#define MyAppExeName "MEFrpLauncherX.exe"

; 相对 installer/：仓库根为 ..
#ifndef PublishDir
  #define PublishDir "..\MEFrpLauncherX\bin\Release\net10.0\win-arm64\publish"
#endif
#ifndef IconFile
  #define IconFile "..\MEFrpLauncherX\Assets\meflx.ico"
#endif
#ifndef OutDir
  #define OutDir "..\dist"
#endif

[Setup]
AppId={{933DF2F8-A81F-429F-B82F-55F9D2EC4D29}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=arm64
ArchitecturesInstallIn64BitMode=arm64
DisableProgramGroupPage=true
PrivilegesRequiredOverridesAllowed=commandline
OutputDir={#OutDir}
OutputBaseFilename=pml2_setup_arm64_{#MyAppVersion}
SetupIconFile={#IconFile}

Compression=lzma2/ultra64
LZMAUseSeparateProcess=yes
LZMANumBlockThreads=2
InternalCompressLevel=ultra
SolidCompression=yes

WizardStyle=modern windows11 dynamic

[Languages]
Name: "Chinese"; MessagesFile: "./Chinese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; CrashDisplayer / Splash 由 CI 构建并放入 publish\Tools\，随递归拷贝安装
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pdb,*.log"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Code]
var
  NoDownloadParam: Boolean;
  CleanupParam: Boolean;

function GetUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
  AppIdValue: String;
begin
  AppIdValue := '{#emit SetupSetting("AppId")}';
  sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\' + AppIdValue + '_is1');
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;

function UnInstallOldVersion(): Boolean;
var
  sUnInstallString: String;
  iResultCode: Integer;
begin
  Result := True;
  sUnInstallString := GetUninstallString();
  if sUnInstallString <> '' then begin
    sUnInstallString := RemoveQuotes(sUnInstallString);
    if Exec(sUnInstallString, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
    begin
      Result := (iResultCode = 0);
      if Result then
        Log('旧版本卸载成功')
      else
        Log('旧版本卸载失败，错误码: ' + IntToStr(iResultCode));
    end
    else
    begin
      Result := False;
      Log('执行卸载程序失败');
    end;
  end
  else
  begin
    Log('未找到旧版本的卸载程序');
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssInstall) and CleanupParam then
  begin
    Log('检测到清理模式，开始检查并卸载旧版本...');
    UnInstallOldVersion();
  end
  else if CurStep = ssInstall then
  begin
    Log('未启用清理模式，跳过旧版本卸载，将直接覆盖安装');
  end;
end;

procedure InitializeWizard();
var
  i: Integer;
  _paramStr: String;
begin
  CleanupParam := False;
  for i := 1 to ParamCount do
  begin
    _paramStr := LowerCase(ParamStr(i));
    if (_paramStr = '/nocleanup') or (_paramStr = '-nocleanup') then
      CleanupParam := False
    else if (_paramStr = '/cleanup') or (_paramStr = '-cleanup') then
      CleanupParam := True;
  end;
end;

function BoolToStr(b: Boolean): String;
begin
  if b then
    Result := 'True'
  else
    Result := 'False';
end;

