; Script generated by the Inno Setup Script Wizard.
; Non-commercial use only
; 路径均相对本脚本所在目录（installer/），本地与 CI 通用。
; CI 可通过 ISCC /DMyAppVersion=... /DOutDir=... 覆盖（配合 #ifndef）。
#include "idp.iss"

#define MyAppName "PML 2"
#ifndef MyAppVersion
  #define MyAppVersion "26.5.0"
#endif
#define MyAppPublisher "RYCB Studio"
#define MyAppURL "https://www.rycb.tech/pml-2"
; 26.5.0：布局改为「启动器 + 版本目录 + 数据目录」，详见 docs/install.md
#define MyAppLauncher "PML 2.exe"
#ifndef LayoutDir
  #define LayoutDir "v26.5.0"
#endif

; 相对 installer/：仓库根为 ..
#ifndef StageDir
  #define StageDir "..\dist\layout"
#endif
#ifndef IconFile
  #define IconFile "..\MEFrpLauncherX\Assets\meflx.ico"
#endif
#ifndef OutDir
  #define OutDir "..\dist"
#endif

[Setup]
AppId={{933DF2F8-A81F-429F-B82F-55F9D2EC4D29}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppLauncher}
ArchitecturesAllowed=arm64
ArchitecturesInstallIn64BitMode=arm64
DisableProgramGroupPage=true
PrivilegesRequiredOverridesAllowed=commandline
OutputDir={#OutDir}
OutputBaseFilename=pml2_setup_arm64_{#MyAppVersion}
SetupIconFile={#IconFile}

Compression=lzma2/ultra64
LZMAUseSeparateProcess=yes
LZMANumBlockThreads=2
InternalCompressLevel=ultra
SolidCompression=yes

WizardStyle=modern windows11 dynamic

[Languages]
Name: "Chinese"; MessagesFile: "./Chinese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; ---- 启动器与版本槽位（安装根直属）----
Source: "{#StageDir}\{#MyAppLauncher}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#StageDir}\launcher.json"; DestDir: "{app}"; Flags: ignoreversion

; ---- 代码：版本目录（只读，升级时被整体替换）----
Source: "{#StageDir}\{#LayoutDir}\*"; DestDir: "{app}\{#LayoutDir}"; \
    Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pdb,*.log,*.dbg,*.mdb"

; ---- 数据：只创建目录骨架，不覆盖已有内容 ----
Source: "{#StageDir}\data\*"; DestDir: "{app}\data"; \
    Flags: ignoreversion recursesubdirs createallsubdirs onlyifdoesntexist uninsneveruninstall

[Dirs]
Name: "{app}\data"; Flags: uninsneveruninstall
Name: "{app}\data\Config"; Flags: uninsneveruninstall
Name: "{app}\data\Config\frp"; Flags: uninsneveruninstall
Name: "{app}\data\Config\Themes"; Flags: uninsneveruninstall
Name: "{app}\data\Config\Plugins"; Flags: uninsneveruninstall
Name: "{app}\data\Config\Certificates"; Flags: uninsneveruninstall
Name: "{app}\data\Cache"; Flags: uninsneveruninstall
Name: "{app}\data\Logs"; Flags: uninsneveruninstall
Name: "{app}\data\Run"; Flags: uninsneveruninstall

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppLauncher}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppLauncher}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppLauncher}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; 只清理代码与启动器；data\ 交由用户决定去留。
Type: filesandordirs; Name: "{app}\{#LayoutDir}"
Type: files; Name: "{app}\{#MyAppLauncher}"
Type: files; Name: "{app}\launcher.json"

[Code]
var
  NoDownloadParam: Boolean;
  CleanupParam: Boolean;

function GetUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
  AppIdValue: String;
begin
  AppIdValue := '{#emit SetupSetting("AppId")}';
  sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\' + AppIdValue + '_is1');
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;

function UnInstallOldVersion(): Boolean;
var
  sUnInstallString: String;
  iResultCode: Integer;
begin
  Result := True;
  sUnInstallString := GetUninstallString();
  if sUnInstallString <> '' then begin
    sUnInstallString := RemoveQuotes(sUnInstallString);
    if Exec(sUnInstallString, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
    begin
      Result := (iResultCode = 0);
      if Result then
        Log('旧版本卸载成功')
      else
        Log('旧版本卸载失败，错误码: ' + IntToStr(iResultCode));
    end
    else
    begin
      Result := False;
      Log('执行卸载程序失败');
    end;
  end
  else
  begin
    Log('未找到旧版本的卸载程序');
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssInstall) and CleanupParam then
  begin
    Log('检测到清理模式，开始检查并卸载旧版本...');
    UnInstallOldVersion();
  end
  else if CurStep = ssInstall then
  begin
    Log('未启用清理模式，跳过旧版本卸载，将直接覆盖安装');
  end;
end;

procedure InitializeWizard();
var
  i: Integer;
  _paramStr: String;
begin
  CleanupParam := False;
  for i := 1 to ParamCount do
  begin
    _paramStr := LowerCase(ParamStr(i));
    if (_paramStr = '/nocleanup') or (_paramStr = '-nocleanup') then
      CleanupParam := False
    else if (_paramStr = '/cleanup') or (_paramStr = '-cleanup') then
      CleanupParam := True;
  end;
end;

function BoolToStr(b: Boolean): String;
begin
  if b then
    Result := 'True'
  else
    Result := 'False';
end;

