; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only
#include "idp.iss"
#define MyAppName "PML 2"
#define MyAppVersion "26.2.0"
#define MyAppPublisher "RYCB Studio"
#define MyAppURL "https://www.rycb.tech/pml-2"
#define MyAppExeName "MEFrpLauncherX.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9B6E9233-5240-4A3F-B392-413051A6840D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=true
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=F:/VSProj/repos/MEFrpLauncherX/MEFrpLauncherX/artifacts/win-x64
OutputBaseFilename=pml2_setup {#MyAppVersion} offline
SetupIconFile=F:/VSProj/repos/MEFrpLauncherX/MEFrpLauncherX/Assets/meflx.ico

; 压缩设置 - 使用最高压缩级别
Compression=lzma2/ultra64
LZMAUseSeparateProcess=yes
LZMANumBlockThreads=2
InternalCompressLevel=ultra
SolidCompression=yes

WizardStyle=modern windows11 dynamic

[Languages]
; Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "Chinese"; MessagesFile: "./Chinese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "F:\VSProj\repos\MEFrpLauncherX\MEFrpLauncherX\bin\Release\net10.0\win-x64\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\VSProj\repos\MEFrpLauncherX\MEFrpLauncherX\bin\Release\net10.0\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pdb,*.log"
Source: ".\RYCB.MEFrpLauncherX.CrashDisplayer.pmla"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Code]
var
  NoDownloadParam: Boolean;
  CleanupParam: Boolean;  // 新增：是否启用清理模式

// ========== 新增：获取旧版本卸载程序路径 ==========
function GetUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
  AppIdValue: String;
begin
  // 获取脚本中定义的 AppId（注意 Inno 会自动添加 _is1 后缀）
  AppIdValue := '{#emit SetupSetting("AppId")}';
  sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\' + AppIdValue + '_is1');
  sUnInstallString := '';
  
  // 从当前用户或所有用户的注册表中读取卸载字符串
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
    
  Result := sUnInstallString;
end;

// ========== 新增：执行卸载旧版本 ==========
function UnInstallOldVersion(): Boolean;
var
  sUnInstallString: String;
  iResultCode: Integer;
begin
  Result := True;
  sUnInstallString := GetUninstallString();
  
  if sUnInstallString <> '' then begin
    // 移除引号
    sUnInstallString := RemoveQuotes(sUnInstallString);
    // 静默执行卸载（/VERYSILENT 比 /SILENT 更安静，不显示任何窗口）
    // 参数说明：
    // /VERYSILENT - 完全静默，不显示卸载进度窗口
    // /NORESTART - 不重启系统
    // /SUPPRESSMSGBOXES - 抑制所有消息框
    if Exec(sUnInstallString, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
    begin
      Result := (iResultCode = 0);  // 0 表示卸载成功
      if Result then
        Log('旧版本卸载成功')
      else
        Log('旧版本卸载失败，错误码: ' + IntToStr(iResultCode));
    end
    else
    begin
      Result := False;
      Log('执行卸载程序失败');
    end;
  end
  else
  begin
    Log('未找到旧版本的卸载程序');
  end;
end;

// ========== 修改：在安装步骤变化时触发卸载（仅当传入 /cleanup 参数时）==========
procedure CurStepChanged(CurStep: TSetupStep);
begin
  // 在开始复制文件之前，如果启用了清理模式，则执行卸载
  if (CurStep = ssInstall) and CleanupParam then
  begin
    Log('检测到 /cleanup 参数，开始检查并卸载旧版本...');
    UnInstallOldVersion();
  end
  else if CurStep = ssInstall then
  begin
    Log('未检测到 /cleanup 参数，跳过旧版本卸载，将直接覆盖安装');
  end;
end;

// ========== 修改：在初始化向导时解析命令行参数 ==========
procedure InitializeWizard();
var
  i: Integer;
  _paramStr: String;
begin
  // 初始化变量
  CleanupParam := False;  // 初始化清理模式为 false
  
  // 检查命令行参数
  for i := 1 to ParamCount do
  begin
    _paramStr := LowerCase(ParamStr(i));
    // 检查 /cleanup 参数（新增）
    if (_paramStr = '/cleanup') or (_paramStr = '-cleanup') then
    begin
      CleanupParam := True;
    end;
  end;
  
  // 可选：在日志中记录参数状态
  //Log('命令行参数解析完成 - NoDownloadParam: ' + BoolToStr(NoDownloadParam) + ', CleanupParam: ' + BoolToStr(CleanupParam));
end;

// 可选：添加一个辅助函数用于布尔值转字符串
function BoolToStr(b: Boolean): String;
begin
  if b then
    Result := 'True'
  else
    Result := 'False';
end;